<?php 
/**
 * Recommendation Selection Panel
 *
 * @since      1.0.0
 * @author     LeoCoder
 */

if (!defined('ABSPATH')) {
    exit;
}
?>

<div class="recommendation-product-options" id="pr-app" data-id="<?php echo $post->ID; ?>">
    <!-- Inner content generated by assets/panel.js -->
</div>