<?php 
/**
 * Recommendation Selection Panel
 *
 * @since      1.0.0
 * @author     LeoCoder
 */

if (!defined('ABSPATH')) {
    exit;
}
?>

<div id="lpr_product_recommendations_panel" class="panel woocommerce_options_panel" style="display: none;">
    <div class="recommendation-product-options" id="pr-app" data-id="<?php echo $post->ID; ?>">
        <!-- Inner content generated by assets/panel.js -->
    </div>
</div>